version: '3.8'

services:
  mysqldb:
     image: mysql
     env_file: ./.env
     environment:
         - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
         - MYSQL_DATABASE=$DB_DATABASE
     ports:
       - $PORT_DB:$PORT_DB
     volumes:
       - ./schemas:/var/lib/mysql  

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - $PORT_SERV:$PORT_SERV          